image: 'php:7.3'

cache:
  paths:
  - vendor/

stages:
  - test
  - deploy

variables:
   APP_ENV: prod

before_script:
  - echo "INSTALLATION"
  - apt-get update
  - apt-get install zip unzip
  - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
  - php composer-setup.php
  - php -r "unlink('composer-setup.php');"
  - php composer.phar install
  - bash ci/docker_install.sh > /dev/null

php_cs_fixer:
  stage: test
  script:
    - "./vendor/bin/php-cs-fixer fix --dry-run --diff --verbose"

#test_unit:
#  stage: test
#  script:
#    - phpunit --configuration phpunit_myapp.xml

production:
  stage: deploy
  script:
  - apt-get update -qy
  - apt-get install -y ruby-dev
  - gem install dpl
  - dpl --provider=heroku --app=gitlab-ci-python-test-prod --api-key=$HEROKU_PRODUCTION_API_KEY
  only:
  - tags