image: docker

services:
  - docker:dind

before_script:
  - docker run -v $PWD:/app composer install

stages:
  - test

php_cs_fixer:
  stage: test
  script:
    - docker pull takamichi/php-cs-fixer
    - docker phpunit tests

unit_test:
  stage: test
  script:
    - docker pull phpunit/phpunit
    - "./bin/phpunit tests"