image: 'php:7.3'

cache:
  paths:
  - vendor/

stages:
  - test
  - deploy

variables:
   APP_ENV: prod

before_script:
  - echo "INSTALLATION"
  - apt-get update
  - apt-get install -y git zip unzip
  - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
  - php composer-setup.php
  - php -r "unlink('composer-setup.php');"
  - php composer.phar install
  - bash ci/docker_install.sh > /dev/null

php_cs_fixer:
  stage: test
  script:
    - "./vendor/bin/php-cs-fixer fix --dry-run --diff --verbose"

production:
  type: deploy
  image : ruby:2.2
  script:
  - apt-get update -qy
  - apt-get install -yqq ruby ruby-dev nodejs --silent
  - gem install dpl
  - dpl --provider=heroku --app=ci-cd-heroku-nodejs --api-  key=$HEROKU_PRODUCTION_API_KEY
  only:
  - master