image: 'php:7.3'

cache:
  paths:
  - vendor/

stages:
  - test

variables:
   APP_ENV: prod

before_script:
   - apt-get update
   - apt-get install zip unzip
   - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
   - php composer-setup.php
   - php -r "unlink('composer-setup.php');"
   - php composer.phar install

test:
  stage: test
  script:
    - "./vendor/bin/php-cs-fixer fix --dry-run --diff --verbose"
    - phpunit tests