image: 'php:7.3'

cache:
  paths:
  - "$HOME/.composer/cache"

stages:
  - test

before_script:
  - docker pull composer
  - docker pull alpine/git

test:
  stage: test
  script:
    - composer install
    - "./vendor/bin/php-cs-fixer fix --dry-run --diff --verbose"
    - phpunit tests