language: 'php'
php:
    - '7.3'

cache:
    directories:
        - $HOME/.composer/cache
    
before_install: true

install:
    - composer install

script:
    - ./vendor/bin/php-cs-fixer fix --dry-run --diff --verbose
    - phpunit tests

deploy:
  provider: heroku
  api_key:
    secure: "ee799555-591e-4a18-a004-a82ff434e110"
  app: shielded-thicket-67247