language: php
php:
  - '7.3'
cache:
  directories:
  - "$HOME/.composer/cache"
before_install: true
install:
  - composer install
script:
  - "./vendor/bin/php-cs-fixer fix --dry-run --diff --verbose"
  - phpunit tests
deploy:
  provider: heroku
  api_key:
    secure: "cmjMf9WP7ZFFowdEGwKR4xvUOtBOZiRRNZhuddiHqTbLwx6NUJcz0Fy2yuEevW+2j8NwitgIKJ71qp69NPE/p+nV1My8gLIGF/h9zy9JpYOQH07NCsaU54D2jW/CNIzs8lOoIWazM4DObLOgeCNoaTUbGltxh0iFl9C6LW6zAkL9lsHdX/RkCp5diHZznDWJaxyVjmWpU/M9LaTJS+kzILxvoWxSPrsrhKnQHVVBOKdJzXDUJA9uZSB4ZyEHc8mJQtxDTuSChuJ8B7quZYi6MGxTXX98hKe/nqIUveE4Pu/qIuv/RpUucEdxyrSPeNCpjg/Ju8ZXxVj+EXEaf17oJtRkk4n+xSBrDOeoR6HaGcyEytPNmWzBmSgu5/ntCy0P+EMvUFZ/xKvfC8tzAvQO1zb5Up1AKyJ6bDKM7q0DuCzCEwIc5BEHkoTAESYOWj7ABQ+zhcvEAKh4mAXn6Ufn/1WoutZWQtOgaFuJL7VU+/EAYXC5RzmjBYJY7J8VGx/n8CbXJA9k63o8zRWqQ+H2YUJL9gin6SaPpMMDYsAjPcPR7N6kIWU7kWw2KxQr+JwlCMaorBEp02c5PbVNMnNfFjd5ay2PJzheyiBXwe1t1g6DatWZFMBLWPENazP2vH1xT7gdxrKQ0bGrPV2+3cJlC+Ov/XR4hqfSUj2GLC/X7Bo="
  app: shielded-thicket-67247
