language: 'php'
php:
    - '7.3'
    
before_install: true

install:
    - composer require friendsofphp/php-cs-fixer --dev
    - composer install

before_script: true

script:
    - ./vendor/bin/php-cs-fixer fix --dry-run --diff
    - phpunit testscomposer global require friendsofphp/php-cs-fixer

after_script: true