language: 'php'
php:
    - '7.3'
    
before_install: true

install:
    - composer install

before_script: true

script:
    - phpunit tests
    - .\vendor\bin\phpcs
    - .\vendor\bin\phpcbf

after_script: true