language: php
php:
- '7.3'
cache:
  directories:
  - "$HOME/.composer/cache"
before_install: true
install:
- composer install
script:
- "./vendor/bin/php-cs-fixer fix --dry-run --diff --verbose"
- phpunit tests
deploy:
  provider: heroku
  api_key:
    secure: Efiv/X2Ynz8HGnGphf5Vm01+A8KJlMLVHYOlOBpqYdzFzmrMzIn2Vsoi6RTjelia5tmPwxG4NeYNQb5e4y392pL3F++brSamSBvW9iviMmeUeP6nwqo6xeMTH7vUaUqF+I65CIAQ3zQUKnsEH7kYO+mbRfcktlTRveI5iC9L811byCcvmKwT9KZ8bgnx3Ji9vSLNM/wtuXHtBnbAaK/dw2Awvq78TIcwZK26gbOhytdTDSXLwyJEw71OimynKQWqb6P5u/jeu8j1h1VFtsVEjuGD0y4Imf2gNfQBjQBijibnS64XvBj7Gwk2+fm3qXWbfVLX5bXtakBkOJ+jecCYnVDHB5cWL1OTyGt0JSZXkeUVz326B6dTIaSh1joXsGbfdBKPp7/PYFYzDEhZAxxuDYr6y+qUUnYbBQsiY4OuHKwQFhkW0YJY76NxAPu0FqDJcx9eUoX3FkPGrHTEUze+xBG/9kSI7BaP8LqC7rALFzh1W7KKG/YwawNiiHC5o7C5p8wsZE79ifbbhSo/lnYWilWTTTasKuvlRRfofGiEISLG23+T2LUlRAexugYBkpuixgBXm+mt/JjlBvLY+Ku8vtirShHOFYpVIUaTpq5m7U6gw709iTs8t/NtZsxCghOBvMxEZKy077shh4l8g7iHCIf6fdYlbHrDABZgkzUyTmY=
  app: shielded-thicket-67247
